File processing pull request
Konor8812/DemoProject1 pull request #2
Opened 2023-01-16 17:34 UTC by Konor8812

2023-01-17 14:00 UTC, meaf requested changes

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/controller/DemoClientController.java
> +        var response = queryProcessingService.performOperation(params);
It is better to compose a response at the controller level, not the service one
```suggestion
        return ResponseEntity.ok(queryProcessingService.performOperation(params));
```

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/IMDbMovieEntity.java
> +        if (attributesList == null) {
extract this long section to a separate method for better readability, or even better initialise it in a static block

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/IMDbMovieParser.java
> +            return null;
if some rows cannot be parsed, we should throw an error

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/QueryProcessingService.java
> +    private String validateParams(Map<String, String> params) {
nit: usually null is returned from validation method if there are no errors

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/controller/DemoClientController.java
> +    public ResponseEntity<Object> performOperation(@RequestParam Map<String, String> params) {
You can specify required params in method signature like so:
@RequestParam(value = "operation", required = true) OperationsRegistry operation

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/QueryProcessingService.java
> +            shouldParse = "true";
never use string representation instead of actual booleans =) 
if you have such strings, convert them before using via Boolean.parseBoolean(..)

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/OperationProcessorException.java
> +public class OperationProcessorException extends RuntimeException{
Why RuntimeException?

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/OperationsRegistry.java
> +    SORT("sort", "sortOperationProcessorUnit"),
You can use new SortOperationProcessorUnit() here

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/ProcessorAssigner.java
> +                            applicationContext.getBean(operationsRegistry.getProcessorName(), OperationProcessor.class))
querying applicationContext directly usually is not welcome, as it indicates that some level of abstraction is lost (if not working with spring internals)
You can also inject required processors here and assign them(or their method reference) depending on the enum value (more conventional then directly with new() in enums)

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/unit/DeleteOperationProcessorUnit.java
> +    public List<IMDbMovieEntity> proceed(List<IMDbMovieEntity> records, Map<String, String> params) throws OperationProcessorException {
simplify this

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/unit/SortOperationProcessorUnit.java
> +            limit = Long.MAX_VALUE;
the more you do fallback behaviours, less predictable your system will be. If there is some error with parsing inputs, better throw an exception

2023-01-17 14:00 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/unit/SortOperationProcessorUnit.java
> +                .sorted((x1, x2) -> compare(x1.getFieldAccessor(attribute), x2.getFieldAccessor(attribute), comparator))
instead of checking asc/desc everywhere, you can use Comparator.reverse()

2023-01-20 13:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/controller/DemoClientController.java
> +        // still unsure where to form ResponseEntities, have questions about it
sure, let's discuss

2023-01-20 13:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/IMDbMovieHolderImpl.java
> +            return null;
Why null is better than empty list here?

2023-01-20 13:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/QueryRequestEntity.java
> +                              @JsonProperty(value = "limit", defaultValue = "0x7fffffffffffffffL") String limit,
usually it is better to default its value like 10/50/100 so it can be displayed in GUI by pages, but here it is ok.

2023-01-20 13:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/QueryRequestEntity.java
> +        System.out.println(validateParamsMsg);
don't forget you have logger

2023-01-20 13:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/QueryRequestEntity.java
> +                              @JsonProperty(value = "shouldParse", defaultValue = "false") String shouldParse,
Since you already create a request class, use typed fields (Long, Boolean etc)

2023-01-20 13:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/QueryRequestEntity.java
> +            responseBuilder.append(" There's no such attribute!");
it would be useful for client to have list of available attributes in response error message

2023-01-20 13:33 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/QueryRequestEntity.java
> +        if(!order.equals("desc")){
add enum for order

2023-01-20 14:10 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/QueryProcessingService.java
> +        if (!shouldParse) {
I would recommend to inline similar variables that are only used once to make method more compact and readable

2023-01-20 14:10 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/ProcessorAssigner.java
> +            case "sort":
Try to avoid strings and use enums in all of your switch statements

2023-01-20 14:10 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/QueryProcessingService.java
> +        var biFunction = processorAssigner.assignProcessor(requestEntity);
nit: inline

2023-01-20 14:10 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/QueryProcessingService.java
> +        var result = biFunction.apply(records, requestEntity);
nit: inline

2023-01-20 14:10 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/QueryProcessingService.java
> +        return ResponseEntity.ok().
don't leave '.' hanging in the end of the line

2023-01-20 14:10 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/unit/OperationProcessor.java
> +    List<IMDbMovieEntity> proceed(List<IMDbMovieEntity> records, QueryRequestEntity requestEntity);
process?

2023-01-24 14:49 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/entity/QueryEntity.java
> +public interface QueryEntity {
abstract class

2023-01-24 14:49 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/registry/OrderRegistry.java
> +    ASC("ASC"),
remove params

2023-01-24 14:49 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/registry/OperationsRegistry.java
> +    SORT("sort"),
remove params

2023-01-24 14:49 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/processor/ProcessorAssigner.java
>                  return null;
throw new exception

2023-01-24 14:49 UTC, meaf commented on demo-client/src/test/java/com/illia/client/model/request/creator/RequestEntityCreatorTest.java
> +        var requestParams = new RequestParams();
extract request jsons to test/resources/

2023-01-24 14:49 UTC, meaf commented on demo-client/src/test/java/com/illia/client/service/QueryProcessingServiceTest.java
> +    public void performOperationTestShouldParseParam(boolean shouldParse) {
split test into two

2023-01-24 14:49 UTC, meaf commented on demo-client/src/test/java/com/illia/client/service/QueryProcessingServiceTest.java
> +    public void performOperationTestFileHolderHoldsFile(boolean fileHolderHoldsFile) {
split

2023-01-24 14:49 UTC, meaf commented on demo-client/src/test/java/com/illia/client/service/processor/ProcessorAssignerTest.java
> +                .thenReturn(OperationsRegistry.getOperation(operation));
valueOf
```suggestion
                .thenReturn(OperationsRegistry.valueOf(operation));
```

2023-01-30 12:08 UTC, meaf requested changes

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/controller/DemoClientController.java
> +    @ExceptionHandler(value = {FileHandlingError.class})
FileHandlingException and FileHandlingError looks very similar and generic so it is hard to tell what is used for what

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/parser/IMDbMovieParser.java
> +            return null;
if the file has invalid lines, we should fail processing with message explaining what went wrong and what should be adjusted in this file

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/parser/IMDbMovieParser.java
> +        if (file.canRead()) {
I suppose if we can't read the file, we should throw some kind of exception

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/parser/IMDbMovieParser.java
> +                e.printStackTrace();
same here: throw an exception?

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/parser/IMDbMovieParser.java
> +        return IMDbMovieEntity.builder()
why don't parse the Integer/Long values immediately?

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/entity/QueryEntity.java
> +    private String fileName;
Why are those private? You want to use those fields for inheritance so you don't declare same fields 3 times

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/file/FileHandlingError.java
> +        super(s);
nit: keep the same naming conventions for your variables: it is 's' here and 'msg' in similar FileHandlingException

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/file/FileTransferService.java
>              var errorMsg = "Inner error while file resolving!";
nit: don't use such disposable variables

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/file/FileTransferService.java
> +                throw new FileHandlingError("Internal error while saving file!");
To me it will be much cleaner if we would throw an exception immediately and not pass some indications that Exception should be thrown (there are multiple places with this issues, find them all 🙃 )

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/file/FileTransferService.java
> +                return serverResponse;
we will have ok() with this message, would this be fine?

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/query/processor/ProcessorAssigner.java
> +    SortOperationProcessorUnit sortOperationProcessorUnit;
nit: use private by default

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/query/processor/unit/SortOperationProcessorUnit.java
> +        var attribute = ((SortQueryEntity) queryEntity).getAttribute();
downcast the query into a new variable at the start of the method to not do this 3 times

2023-01-30 12:08 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/query/processor/unit/SortOperationProcessorUnit.java
> +        boolean shouldOrderAsc = ((SortQueryEntity) queryEntity).getOrder().equals(OrderRegistry.ASC);
tip: you can use == with Enums (and some Strings, but less reliable)

2023-01-30 16:28 UTC, Konor8812 commented on demo-client/src/main/java/com/illia/client/controller/DemoClientController.java
> +    @ExceptionHandler(value = {FileHandlingError.class})
FileHandlingException was designed to 'represent' 4xx status code. It notifies user about invalid input or resource absence.
FileHandlingError 'represents' 5xx  errors

2023-02-09 15:17 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/holder/IMDbMovieHolderImpl.java
> +    public boolean isEmpty() {
nit: it is not used

2023-02-09 15:18 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/holder/IMDbMovieHolderImpl.java
> +            return null;
forgot to throw an immediate exception here

2023-02-09 15:20 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/holder/IMDbMovieHolderImpl.java
> +        if(!holdsFile(fileName) || entities.isEmpty()){
It is a possible case that there are no entries in the file, therefore no entities, therefore not an exception case

2023-02-09 15:33 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/parser/IMDbMovieParser.java
> +            throw new FileHandlingError("Server error while reading file!");
always log such exceptions!

2023-02-09 15:35 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/entity/SortQueryEntity.java
> +@EqualsAndHashCode(callSuper = false)
why false?

2023-02-09 15:38 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/entity/SortQueryEntity.java
> +    public String getFileName() {
you don't need to override them. Also, if you use lombok's Data annotation you don't even need any getters/setters for parent/child class

2023-02-13 16:29 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/holder/IMDbMovieHolderImpl.java
> +        if(holdsFile(fileName) && !entities.isEmpty()){
are you sure? if we have file and have entities it is an exception? =)

2023-02-13 16:29 UTC, meaf commented on demo-client/src/main/java/com/illia/client/model/request/entity/SortQueryEntity.java
>      private long limit;
is it working? afaik jackson needs setters to set the private field

2023-02-13 16:29 UTC, meaf commented on demo-client/src/main/java/com/illia/client/service/query/QueryProcessingService.java
> +            }catch (FileHandlingException ex){ // reasonable exceptions convention?
it is better not to use if possible, but I'd not restrict that

2023-02-14 14:14 UTC, meaf approved these changes

2023-02-14 14:15 UTC, merged